name: kalman-ir
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - setuptools
  - packaging=23
  - pip
  - wheel
  - numpy=1.26.4
  - pytorch=2.2.2
  - pytorch-cuda=11.8
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - torchtriton
  - mkl=2023.1.0
  - pip:
      - regex
      - pyyaml==6.0.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - zipp
      - tqdm
      - cachetools==5.3.3
      - cmake==3.28.3
      - ninja==1.11.1.1
      - lit==17.0.6
      - einops==0.7.0
      - scipy==1.12
      - scikit-image==0.22.0
      - markdown
      - matplotlib==3.9.0
      - tensorboard==2.14.0
      - safetensors==0.4.2
      - huggingface-hub==0.21.1
      - opencv-python-headless==4.10.0.82
      - albumentations==2.0.8
      - imageio
      - lpips==0.1.4
      - timm==0.9.16
      - diffusers==0.13.1
      - tokenizers==0.15.2
      - transformers==4.38.1
      - causal-conv1d==1.2.1
      - mamba-ssm==1.2.2
      # - optuna
