name: mamba-ir
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8.18
  - setuptools=68.2.2
  - packaging=23.2
  - pip
  - wheel
  - numpy=1.24.3
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - torchtriton=2.0.0
  - mkl
  - tk
  - typing_extensions
  - pip:
      - regex
      - pyyaml==6.0.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - zipp==3.17.0
      - tqdm
      - cachetools==5.3.3
      - cmake==3.28.3
      - lit==17.0.6
      - ninja==1.11.1.1
      - einops==0.7.0
      - scipy==1.10.1
      - scikit-image==0.21.0
      - markdown
      - matplotlib==3.7.5
      - tensorboard==2.18.0
      - safetensors==0.4.2
      - huggingface-hub==0.21.1
      - opencv-python-headless==4.10.0.82
      - imageio
      - lpips==0.1.4
      - timm==0.9.16
      - diffusers==0.11.0
      - tokenizers==0.15.2
      - transformers==4.38.1
      - causal-conv1d==1.0.0
      - mamba-ssm==1.0.1
